import type { PrivatePerpProof } from "../types";

/**
 * Hardcoded perpetual position proofs for demo purposes
 * In production, these would be generated by actual ZK circuits
 */
export const DEMO_PERP_PROOFS: Record<string, PrivatePerpProof> = {
  // 5x Long FLR-USD $1000
  "long-flr-5x-1000": {
    protocol: "groth16",
    actionType: "perp",
    proof: {
      pi_a: [
        "0x789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567",
        "0x89abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678",
      ],
      pi_b: [
        [
          "0x9abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789",
          "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
        ],
        [
          "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678901",
          "0xcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789012",
        ],
      ],
      pi_c: [
        "0xdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890123",
        "0xef1234567890abcdef1234567890abcdef1234567890abcdef12345678901234",
      ],
    },
    publicSignals: [
      "42", // ertId
      "1705678903", // timestamp
      "1", // hasPosition
      "1", // leverageWithinLimit
      "1", // sizeWithinLimit
      "1", // marketAllowed
    ],
    proofHash: "0x789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678903,
      hasPosition: true,
    },
    privateInputs: {
      market: "FLR-USD",
      size: BigInt("1000000000"), // $1000 position size (6 decimals)
      leverage: 5,
      isLong: true,
      collateral: BigInt("200000000"), // $200 collateral
    },
    attestations: {
      ertOwnership: true,
      leverageWithinLimit: true,
      sizeWithinLimit: true,
      marketAllowed: true,
    },
  },

  // 3x Short FLR-USD $500
  "short-flr-3x-500": {
    protocol: "groth16",
    actionType: "perp",
    proof: {
      pi_a: [
        "0x89abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234568",
        "0x9abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345679",
      ],
      pi_b: [
        [
          "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678a",
          "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789a1",
        ],
        [
          "0xcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678902",
          "0xdef1234567890abcdef1234567890abcdef1234567890abcdef123456789013",
        ],
      ],
      pi_c: [
        "0xef1234567890abcdef1234567890abcdef1234567890abcdef1234567890124",
        "0xf1234567890abcdef1234567890abcdef1234567890abcdef123456789012345",
      ],
    },
    publicSignals: [
      "42",
      "1705678904",
      "1",
      "1",
      "1",
      "1",
    ],
    proofHash: "0x89abcdef1234567890abcdef1234567890abcdef1234567890abcdef1235",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678904,
      hasPosition: true,
    },
    privateInputs: {
      market: "FLR-USD",
      size: BigInt("500000000"), // $500 position size
      leverage: 3,
      isLong: false, // SHORT
      collateral: BigInt("166666667"), // ~$166.67 collateral
    },
    attestations: {
      ertOwnership: true,
      leverageWithinLimit: true,
      sizeWithinLimit: true,
      marketAllowed: true,
    },
  },

  // 2x Long BTC-USD $2000
  "long-btc-2x-2000": {
    protocol: "groth16",
    actionType: "perp",
    proof: {
      pi_a: [
        "0x9abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234569",
        "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567a",
      ],
      pi_b: [
        [
          "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678b",
          "0xcdef1234567890abcdef1234567890abcdef1234567890abcdef123456789a2",
        ],
        [
          "0xdef1234567890abcdef1234567890abcdef1234567890abcdef12345678903",
          "0xef1234567890abcdef1234567890abcdef1234567890abcdef123456789014",
        ],
      ],
      pi_c: [
        "0xf1234567890abcdef1234567890abcdef1234567890abcdef1234567890125",
        "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890123456",
      ],
    },
    publicSignals: [
      "42",
      "1705678905",
      "1",
      "1",
      "1",
      "1",
    ],
    proofHash: "0x9abcdef1234567890abcdef1234567890abcdef1234567890abcdef1236",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678905,
      hasPosition: true,
    },
    privateInputs: {
      market: "BTC-USD",
      size: BigInt("2000000000"), // $2000 position size
      leverage: 2,
      isLong: true,
      collateral: BigInt("1000000000"), // $1000 collateral
    },
    attestations: {
      ertOwnership: true,
      leverageWithinLimit: true,
      sizeWithinLimit: true,
      marketAllowed: true,
    },
  },

  // Close position proof
  "close-position": {
    protocol: "groth16",
    actionType: "perp",
    proof: {
      pi_a: [
        "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef123456a",
        "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567b",
      ],
      pi_b: [
        [
          "0xcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678c",
          "0xdef1234567890abcdef1234567890abcdef1234567890abcdef123456789a3",
        ],
        [
          "0xef1234567890abcdef1234567890abcdef1234567890abcdef12345678904",
          "0xf1234567890abcdef1234567890abcdef1234567890abcdef123456789015",
        ],
      ],
      pi_c: [
        "0x234567890abcdef1234567890abcdef1234567890abcdef1234567890126",
        "0x34567890abcdef1234567890abcdef1234567890abcdef12345678901234567",
      ],
    },
    publicSignals: [
      "42",
      "1705678906",
      "0", // hasPosition = false (closing)
      "1",
      "1",
      "1",
    ],
    proofHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1237",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678906,
      hasPosition: false,
    },
    privateInputs: {
      market: "FLR-USD",
      size: BigInt("0"), // Closing
      leverage: 0,
      isLong: true,
      collateral: BigInt("0"),
    },
    attestations: {
      ertOwnership: true,
      leverageWithinLimit: true,
      sizeWithinLimit: true,
      marketAllowed: true,
    },
  },

  // Default fallback proof
  "default": {
    protocol: "groth16",
    actionType: "perp",
    proof: {
      pi_a: [
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
      ],
      pi_b: [
        [
          "0x0000000000000000000000000000000000000000000000000000000000000003",
          "0x0000000000000000000000000000000000000000000000000000000000000004",
        ],
        [
          "0x0000000000000000000000000000000000000000000000000000000000000005",
          "0x0000000000000000000000000000000000000000000000000000000000000006",
        ],
      ],
      pi_c: [
        "0x0000000000000000000000000000000000000000000000000000000000000007",
        "0x0000000000000000000000000000000000000000000000000000000000000008",
      ],
    },
    publicSignals: ["0", "0", "1", "1", "1", "1"],
    proofHash: "0x0000000000000000000000000000000000000000000000000000000000000002",
    publicInputs: {
      ertId: 0,
      timestamp: 0,
      hasPosition: false,
    },
    privateInputs: {
      market: "FLR-USD",
      size: BigInt(0),
      leverage: 1,
      isLong: true,
      collateral: BigInt(0),
    },
    attestations: {
      ertOwnership: true,
      leverageWithinLimit: true,
      sizeWithinLimit: true,
      marketAllowed: true,
    },
  },
};

/**
 * Get a perp proof by key or return default
 */
export function getPerpProof(key: string): PrivatePerpProof {
  return DEMO_PERP_PROOFS[key] || DEMO_PERP_PROOFS["default"];
}
