import type { PrivateSettlementProof } from "../types";

/**
 * Hardcoded settlement proofs for demo purposes
 * In production, these would be generated by actual ZK circuits
 */
export const DEMO_SETTLEMENT_PROOFS: Record<string, PrivateSettlementProof> = {
  // Settlement with +15% profit
  "settlement-positive-15": {
    protocol: "groth16",
    actionType: "settlement",
    proof: {
      pi_a: [
        "0xdef123456789abcdef1234567890abcdef1234567890abcdef1234567890abc",
        "0xef123456789abcdef1234567890abcdef1234567890abcdef1234567890abcd",
      ],
      pi_b: [
        [
          "0xf123456789abcdef1234567890abcdef1234567890abcdef1234567890abcde",
          "0x123456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
        ],
        [
          "0x23456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1",
          "0x3456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef12",
        ],
      ],
      pi_c: [
        "0x456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef123",
        "0x56789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234",
      ],
    },
    publicSignals: [
      "42", // ertId
      "5000000000", // starting capital (5000 USDC)
      "5750000000", // ending capital (5750 USDC)
      "750000000", // pnl (+750 USDC)
      "12345678", // FTSO price block
      "150000000", // LP share ($150)
      "600000000", // Executor share ($600)
    ],
    proofHash: "0xdef123456789abcdef1234567890abcdef1234567890abcdef1234567890",
    publicInputs: {
      ertId: 42,
      startingCapital: BigInt("5000000000"), // 5000 USDC
      endingCapital: BigInt("5750000000"), // 5750 USDC
      pnl: BigInt("750000000"), // +750 USDC (15% profit)
      ftsoPriceBlock: 12345678,
      lpShare: BigInt("150000000"), // $150 (20% of profit)
      executorShare: BigInt("600000000"), // $600 (80% of profit)
    },
    privateInputs: {
      tradeHistory: [
        {
          timestamp: 1705678901,
          tokenIn: "WFLR",
          tokenOut: "USDC",
          amountIn: BigInt("1000000000000000000000"),
          amountOut: BigInt("1020000000"),
          adapter: "MockSimpleDEX",
        },
        {
          timestamp: 1705678950,
          tokenIn: "USDC",
          tokenOut: "WFLR",
          amountIn: BigInt("1020000000"),
          amountOut: BigInt("1080000000000000000000"),
          adapter: "MockSimpleDEX",
        },
      ],
      positionHistory: [
        {
          openTimestamp: 1705678960,
          closeTimestamp: 1705679000,
          market: "FLR-USD",
          size: BigInt("1000000000"),
          leverage: 5,
          isLong: true,
          entryPrice: BigInt("950000"), // $0.95
          exitPrice: BigInt("1020000"), // $1.02
          pnl: BigInt("368421052"), // ~$368 profit
        },
      ],
    },
    attestations: {
      pnlCalculatedCorrectly: true,
      ftsoPricesUsed: true,
      allTradesWithinConstraints: true,
      feeDistributionCorrect: true,
    },
  },

  // Settlement with -5% loss
  "settlement-negative-5": {
    protocol: "groth16",
    actionType: "settlement",
    proof: {
      pi_a: [
        "0xef123456789abcdef1234567890abcdef1234567890abcdef1234567890abd",
        "0xf123456789abcdef1234567890abcdef1234567890abcdef1234567890abce",
      ],
      pi_b: [
        [
          "0x123456789abcdef1234567890abcdef1234567890abcdef1234567890abcdf",
          "0x23456789abcdef1234567890abcdef1234567890abcdef1234567890abcdf0",
        ],
        [
          "0x3456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef2",
          "0x456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef13",
        ],
      ],
      pi_c: [
        "0x56789abcdef1234567890abcdef1234567890abcdef1234567890abcdef124",
        "0x6789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1235",
      ],
    },
    publicSignals: [
      "42",
      "5000000000", // starting capital
      "4750000000", // ending capital (lost $250)
      "-250000000", // pnl (-$250)
      "12345700",
      "0", // LP share (no profit to share)
      "0", // Executor share
    ],
    proofHash: "0xef123456789abcdef1234567890abcdef1234567890abcdef1234567891",
    publicInputs: {
      ertId: 42,
      startingCapital: BigInt("5000000000"),
      endingCapital: BigInt("4750000000"),
      pnl: BigInt("-250000000"), // -$250 (5% loss)
      ftsoPriceBlock: 12345700,
      lpShare: BigInt("0"), // No profit sharing on loss
      executorShare: BigInt("0"),
    },
    privateInputs: {
      tradeHistory: [
        {
          timestamp: 1705679001,
          tokenIn: "WFLR",
          tokenOut: "USDC",
          amountIn: BigInt("2000000000000000000000"),
          amountOut: BigInt("1900000000"),
          adapter: "MockSimpleDEX",
        },
      ],
      positionHistory: [],
    },
    attestations: {
      pnlCalculatedCorrectly: true,
      ftsoPricesUsed: true,
      allTradesWithinConstraints: true,
      feeDistributionCorrect: true,
    },
  },

  // Settlement with +50% profit (high performance)
  "settlement-positive-50": {
    protocol: "groth16",
    actionType: "settlement",
    proof: {
      pi_a: [
        "0xf123456789abcdef1234567890abcdef1234567890abcdef1234567890abe",
        "0x0123456789abcdef1234567890abcdef1234567890abcdef1234567890abcf",
      ],
      pi_b: [
        [
          "0x23456789abcdef1234567890abcdef1234567890abcdef1234567890abcd0",
          "0x3456789abcdef1234567890abcdef1234567890abcdef1234567890abcdf1",
        ],
        [
          "0x456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef3",
          "0x56789abcdef1234567890abcdef1234567890abcdef1234567890abcdef14",
        ],
      ],
      pi_c: [
        "0x6789abcdef1234567890abcdef1234567890abcdef1234567890abcdef125",
        "0x789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1236",
      ],
    },
    publicSignals: [
      "42",
      "5000000000",
      "7500000000", // +50% = 7500 USDC
      "2500000000", // +$2500 profit
      "12345800",
      "500000000", // LP share ($500)
      "2000000000", // Executor share ($2000)
    ],
    proofHash: "0xf123456789abcdef1234567890abcdef1234567890abcdef1234567892",
    publicInputs: {
      ertId: 42,
      startingCapital: BigInt("5000000000"),
      endingCapital: BigInt("7500000000"),
      pnl: BigInt("2500000000"), // +$2500 (50% profit)
      ftsoPriceBlock: 12345800,
      lpShare: BigInt("500000000"), // $500 (20%)
      executorShare: BigInt("2000000000"), // $2000 (80%)
    },
    privateInputs: {
      tradeHistory: [
        {
          timestamp: 1705679010,
          tokenIn: "WFLR",
          tokenOut: "USDC",
          amountIn: BigInt("5000000000000000000000"),
          amountOut: BigInt("5500000000"),
          adapter: "MockSimpleDEX",
        },
        {
          timestamp: 1705679100,
          tokenIn: "USDC",
          tokenOut: "WFLR",
          amountIn: BigInt("5500000000"),
          amountOut: BigInt("6500000000000000000000"),
          adapter: "MockSimpleDEX",
        },
        {
          timestamp: 1705679200,
          tokenIn: "WFLR",
          tokenOut: "USDC",
          amountIn: BigInt("6500000000000000000000"),
          amountOut: BigInt("7500000000"),
          adapter: "MockSimpleDEX",
        },
      ],
      positionHistory: [],
    },
    attestations: {
      pnlCalculatedCorrectly: true,
      ftsoPricesUsed: true,
      allTradesWithinConstraints: true,
      feeDistributionCorrect: true,
    },
  },

  // Settlement at breakeven
  "settlement-breakeven": {
    protocol: "groth16",
    actionType: "settlement",
    proof: {
      pi_a: [
        "0x0123456789abcdef1234567890abcdef1234567890abcdef1234567890abf",
        "0x123456789abcdef1234567890abcdef1234567890abcdef1234567890abd0",
      ],
      pi_b: [
        [
          "0x3456789abcdef1234567890abcdef1234567890abcdef1234567890abcd1",
          "0x456789abcdef1234567890abcdef1234567890abcdef1234567890abcdf2",
        ],
        [
          "0x56789abcdef1234567890abcdef1234567890abcdef1234567890abcdef4",
          "0x6789abcdef1234567890abcdef1234567890abcdef1234567890abcdef15",
        ],
      ],
      pi_c: [
        "0x789abcdef1234567890abcdef1234567890abcdef1234567890abcdef126",
        "0x89abcdef1234567890abcdef1234567890abcdef1234567890abcdef1237",
      ],
    },
    publicSignals: [
      "42",
      "5000000000",
      "5000000000",
      "0", // Breakeven
      "12345900",
      "0",
      "0",
    ],
    proofHash: "0x0123456789abcdef1234567890abcdef1234567890abcdef1234567893",
    publicInputs: {
      ertId: 42,
      startingCapital: BigInt("5000000000"),
      endingCapital: BigInt("5000000000"),
      pnl: BigInt("0"), // Breakeven
      ftsoPriceBlock: 12345900,
      lpShare: BigInt("0"),
      executorShare: BigInt("0"),
    },
    privateInputs: {
      tradeHistory: [],
      positionHistory: [],
    },
    attestations: {
      pnlCalculatedCorrectly: true,
      ftsoPricesUsed: true,
      allTradesWithinConstraints: true,
      feeDistributionCorrect: true,
    },
  },

  // Default fallback proof
  "default": {
    protocol: "groth16",
    actionType: "settlement",
    proof: {
      pi_a: [
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
      ],
      pi_b: [
        [
          "0x0000000000000000000000000000000000000000000000000000000000000003",
          "0x0000000000000000000000000000000000000000000000000000000000000004",
        ],
        [
          "0x0000000000000000000000000000000000000000000000000000000000000005",
          "0x0000000000000000000000000000000000000000000000000000000000000006",
        ],
      ],
      pi_c: [
        "0x0000000000000000000000000000000000000000000000000000000000000007",
        "0x0000000000000000000000000000000000000000000000000000000000000008",
      ],
    },
    publicSignals: ["0", "0", "0", "0", "0", "0", "0"],
    proofHash: "0x0000000000000000000000000000000000000000000000000000000000000003",
    publicInputs: {
      ertId: 0,
      startingCapital: BigInt("0"),
      endingCapital: BigInt("0"),
      pnl: BigInt("0"),
      ftsoPriceBlock: 0,
      lpShare: BigInt("0"),
      executorShare: BigInt("0"),
    },
    privateInputs: {
      tradeHistory: [],
      positionHistory: [],
    },
    attestations: {
      pnlCalculatedCorrectly: true,
      ftsoPricesUsed: true,
      allTradesWithinConstraints: true,
      feeDistributionCorrect: true,
    },
  },
};

/**
 * Get a settlement proof by key or return default
 */
export function getSettlementProof(key: string): PrivateSettlementProof {
  return DEMO_SETTLEMENT_PROOFS[key] || DEMO_SETTLEMENT_PROOFS["default"];
}
