import type { PrivateSwapProof } from "../types";

/**
 * Hardcoded swap proofs for demo purposes
 * In production, these would be generated by actual ZK circuits
 */
export const DEMO_SWAP_PROOFS: Record<string, PrivateSwapProof> = {
  // Swap 1000 WFLR -> USDC via MockSimpleDEX
  "wflr-usdc-1000": {
    protocol: "groth16",
    actionType: "swap",
    proof: {
      pi_a: [
        "0x1a2b3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890",
        "0x3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcd",
      ],
      pi_b: [
        [
          "0x5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12",
          "0x7a8b9c0d1e2f3456789012345678901234567890123456789012345678901234",
        ],
        [
          "0x9c0d1e2f34567890123456789012345678901234567890123456789012345678",
          "0xef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcd",
        ],
      ],
      pi_c: [
        "0x3456789012345678901234567890123456789012345678901234567890123456",
        "0x7890123456789012345678901234567890123456789012345678901234567890",
      ],
    },
    publicSignals: [
      "42", // ertId
      "1705678901", // timestamp
      "1", // adapterAllowed
      "1", // assetsAllowed
      "1", // amountWithinLimit
    ],
    proofHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678901,
    },
    privateInputs: {
      tokenIn: "0x0a22b6e2f0ac6cDA83C04B1Ba33aAc8e9Df6aed7", // MockWFLR
      tokenOut: "0x9401FCe40Cb84b051215d96e85BecD733043a33D", // MockUSDC
      amountIn: BigInt("1000000000000000000000"), // 1000 WFLR
      minAmountOut: BigInt("980000000"), // ~980 USDC (allowing 2% slippage)
      adapter: "0x5F2577675beD125794FDC44940b62D60BF00F81", // MockSimpleDEX
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetsAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Swap 500 USDC -> WFLR via MockSimpleDEX
  "usdc-wflr-500": {
    protocol: "groth16",
    actionType: "swap",
    proof: {
      pi_a: [
        "0x2b3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567891",
        "0x4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abce",
      ],
      pi_b: [
        [
          "0x6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef13",
          "0x8b9c0d1e2f3456789012345678901234567890123456789012345678901235",
        ],
        [
          "0xd1e2f34567890123456789012345678901234567890123456789012345679",
          "0x234567890abcdef1234567890abcdef1234567890abcdef1234567890abce",
        ],
      ],
      pi_c: [
        "0x56789012345678901234567890123456789012345678901234567890123457",
        "0x90123456789012345678901234567890123456789012345678901234567891",
      ],
    },
    publicSignals: [
      "42",
      "1705678902",
      "1",
      "1",
      "1",
    ],
    proofHash: "0xbcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567891",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678902,
    },
    privateInputs: {
      tokenIn: "0x9401FCe40Cb84b051215d96e85BecD733043a33D", // MockUSDC
      tokenOut: "0x0a22b6e2f0ac6cDA83C04B1Ba33aAc8e9Df6aed7", // MockWFLR
      amountIn: BigInt("500000000"), // 500 USDC
      minAmountOut: BigInt("490000000000000000000"), // ~490 WFLR
      adapter: "0x5F2577675beD125794FDC44940b62D60BF00F81",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetsAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Swap 2000 WFLR -> USDC (larger trade)
  "wflr-usdc-2000": {
    protocol: "groth16",
    actionType: "swap",
    proof: {
      pi_a: [
        "0x3c4d5e6f7890abcdef1234567890abcdef1234567890abcdef1234567892",
        "0x5e6f7890abcdef1234567890abcdef1234567890abcdef1234567890abcf",
      ],
      pi_b: [
        [
          "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef14",
          "0x9c0d1e2f3456789012345678901234567890123456789012345678901236",
        ],
        [
          "0xe2f34567890123456789012345678901234567890123456789012345670a",
          "0x34567890abcdef1234567890abcdef1234567890abcdef1234567890abcf",
        ],
      ],
      pi_c: [
        "0x6789012345678901234567890123456789012345678901234567890123458",
        "0xa0123456789012345678901234567890123456789012345678901234567892",
      ],
    },
    publicSignals: [
      "42",
      "1705678903",
      "1",
      "1",
      "1",
    ],
    proofHash: "0xcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567892",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678903,
    },
    privateInputs: {
      tokenIn: "0x0a22b6e2f0ac6cDA83C04B1Ba33aAc8e9Df6aed7",
      tokenOut: "0x9401FCe40Cb84b051215d96e85BecD733043a33D",
      amountIn: BigInt("2000000000000000000000"), // 2000 WFLR
      minAmountOut: BigInt("1960000000"), // ~1960 USDC
      adapter: "0x5F2577675beD125794FDC44940b62D60BF00F81",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetsAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Default fallback proof
  "default": {
    protocol: "groth16",
    actionType: "swap",
    proof: {
      pi_a: [
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
      ],
      pi_b: [
        [
          "0x0000000000000000000000000000000000000000000000000000000000000003",
          "0x0000000000000000000000000000000000000000000000000000000000000004",
        ],
        [
          "0x0000000000000000000000000000000000000000000000000000000000000005",
          "0x0000000000000000000000000000000000000000000000000000000000000006",
        ],
      ],
      pi_c: [
        "0x0000000000000000000000000000000000000000000000000000000000000007",
        "0x0000000000000000000000000000000000000000000000000000000000000008",
      ],
    },
    publicSignals: ["0", "0", "1", "1", "1"],
    proofHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
    publicInputs: {
      ertId: 0,
      timestamp: 0,
    },
    privateInputs: {
      tokenIn: "0x0000000000000000000000000000000000000000",
      tokenOut: "0x0000000000000000000000000000000000000000",
      amountIn: BigInt(0),
      minAmountOut: BigInt(0),
      adapter: "0x0000000000000000000000000000000000000000",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetsAllowed: true,
      amountWithinLimit: true,
    },
  },
};

/**
 * Get a swap proof by key or return default
 */
export function getSwapProof(key: string): PrivateSwapProof {
  return DEMO_SWAP_PROOFS[key] || DEMO_SWAP_PROOFS["default"];
}
