import type { PrivateYieldProof } from "../types";

/**
 * Hardcoded yield proofs for demo purposes
 * In production, these would be generated by actual ZK circuits
 */
export const DEMO_YIELD_PROOFS: Record<string, PrivateYieldProof> = {
  // Stake 2000 FLR via MockSceptre
  "stake-flr-2000": {
    protocol: "groth16",
    actionType: "yield",
    proof: {
      pi_a: [
        "0xa1b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890",
        "0xb2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890ab",
      ],
      pi_b: [
        [
          "0xc3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcd",
          "0xd4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcde1",
        ],
        [
          "0xe5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12",
          "0xf67890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234",
        ],
      ],
      pi_c: [
        "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123456",
        "0x90abcdef1234567890abcdef1234567890abcdef1234567890abcdef12345678",
      ],
    },
    publicSignals: [
      "42", // ertId
      "1705678902", // timestamp
      "1", // adapterAllowed
      "1", // assetAllowed
      "1", // amountWithinLimit
      "1", // ertOwnership
    ],
    proofHash: "0x123456abcdef1234567890abcdef1234567890abcdef1234567890abcdef12",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678902,
      protocol: "staking",
    },
    privateInputs: {
      adapter: "0x8C6057145c1C523e08D3D1dCbaC77925Ee25f46D", // MockSceptre
      asset: "0x0a22b6e2f0ac6cDA83C04B1Ba33aAc8e9Df6aed7", // MockWFLR
      amount: BigInt("2000000000000000000000"), // 2000 FLR
      action: "stake",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Unstake 1000 sFLR via MockSceptre
  "unstake-sflr-1000": {
    protocol: "groth16",
    actionType: "yield",
    proof: {
      pi_a: [
        "0xb2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567891",
        "0xc3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890ac",
      ],
      pi_b: [
        [
          "0xd4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890abce",
          "0xe5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcde2",
        ],
        [
          "0xf67890abcdef1234567890abcdef1234567890abcdef1234567890abcdef13",
          "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1235",
        ],
      ],
      pi_c: [
        "0x890abcdef1234567890abcdef1234567890abcdef1234567890abcdef123457",
        "0xa0bcdef1234567890abcdef1234567890abcdef1234567890abcdef12345679",
      ],
    },
    publicSignals: [
      "42",
      "1705678903",
      "1",
      "1",
      "1",
      "1",
    ],
    proofHash: "0x234567abcdef1234567890abcdef1234567890abcdef1234567890abcdef13",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678903,
      protocol: "staking",
    },
    privateInputs: {
      adapter: "0x8C6057145c1C523e08D3D1dCbaC77925Ee25f46D",
      asset: "0x8C6057145c1C523e08D3D1dCbaC77925Ee25f46D", // sFLR (same as Sceptre for simplicity)
      amount: BigInt("1000000000000000000000"), // 1000 sFLR
      action: "unstake",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Supply 5000 USDC to MockKinetic
  "supply-usdc-5000": {
    protocol: "groth16",
    actionType: "yield",
    proof: {
      pi_a: [
        "0xc3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567892",
        "0xd4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890ad",
      ],
      pi_b: [
        [
          "0xe5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcf",
          "0xf67890abcdef1234567890abcdef1234567890abcdef1234567890abcde3",
        ],
        [
          "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcdef14",
          "0x890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1236",
        ],
      ],
      pi_c: [
        "0x90abcdef1234567890abcdef1234567890abcdef1234567890abcdef123458",
        "0xb0cdef1234567890abcdef1234567890abcdef1234567890abcdef1234567a",
      ],
    },
    publicSignals: [
      "42",
      "1705678904",
      "1",
      "1",
      "1",
      "1",
    ],
    proofHash: "0x345678abcdef1234567890abcdef1234567890abcdef1234567890abcdef14",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678904,
      protocol: "lending",
    },
    privateInputs: {
      adapter: "0xf59C5d72cAA0875788fD9461488b4daC7d5EdA1f", // MockKinetic
      asset: "0x9401FCe40Cb84b051215d96e85BecD733043a33D", // MockUSDC
      amount: BigInt("5000000000"), // 5000 USDC (6 decimals)
      action: "supply",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Withdraw 3000 USDC from MockKinetic
  "withdraw-usdc-3000": {
    protocol: "groth16",
    actionType: "yield",
    proof: {
      pi_a: [
        "0xd4e5f67890abcdef1234567890abcdef1234567890abcdef1234567893",
        "0xe5f67890abcdef1234567890abcdef1234567890abcdef1234567890ae",
      ],
      pi_b: [
        [
          "0xf67890abcdef1234567890abcdef1234567890abcdef1234567890abd0",
          "0x7890abcdef1234567890abcdef1234567890abcdef1234567890abcde4",
        ],
        [
          "0x890abcdef1234567890abcdef1234567890abcdef1234567890abcdef15",
          "0x90abcdef1234567890abcdef1234567890abcdef1234567890abcdef1237",
        ],
      ],
      pi_c: [
        "0xa0bcdef1234567890abcdef1234567890abcdef1234567890abcdef123459",
        "0xc0def1234567890abcdef1234567890abcdef1234567890abcdef1234567b",
      ],
    },
    publicSignals: [
      "42",
      "1705678905",
      "1",
      "1",
      "1",
      "1",
    ],
    proofHash: "0x456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef15",
    publicInputs: {
      ertId: 42,
      timestamp: 1705678905,
      protocol: "lending",
    },
    privateInputs: {
      adapter: "0xf59C5d72cAA0875788fD9461488b4daC7d5EdA1f",
      asset: "0x9401FCe40Cb84b051215d96e85BecD733043a33D",
      amount: BigInt("3000000000"), // 3000 USDC
      action: "withdraw",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetAllowed: true,
      amountWithinLimit: true,
    },
  },

  // Default fallback proof
  "default": {
    protocol: "groth16",
    actionType: "yield",
    proof: {
      pi_a: [
        "0x0000000000000000000000000000000000000000000000000000000000000001",
        "0x0000000000000000000000000000000000000000000000000000000000000002",
      ],
      pi_b: [
        [
          "0x0000000000000000000000000000000000000000000000000000000000000003",
          "0x0000000000000000000000000000000000000000000000000000000000000004",
        ],
        [
          "0x0000000000000000000000000000000000000000000000000000000000000005",
          "0x0000000000000000000000000000000000000000000000000000000000000006",
        ],
      ],
      pi_c: [
        "0x0000000000000000000000000000000000000000000000000000000000000007",
        "0x0000000000000000000000000000000000000000000000000000000000000008",
      ],
    },
    publicSignals: ["0", "0", "1", "1", "1", "1"],
    proofHash: "0x0000000000000000000000000000000000000000000000000000000000000001",
    publicInputs: {
      ertId: 0,
      timestamp: 0,
      protocol: "staking",
    },
    privateInputs: {
      adapter: "0x0000000000000000000000000000000000000000",
      asset: "0x0000000000000000000000000000000000000000",
      amount: BigInt(0),
      action: "stake",
    },
    attestations: {
      ertOwnership: true,
      adapterAllowed: true,
      assetAllowed: true,
      amountWithinLimit: true,
    },
  },
};

/**
 * Get a yield proof by key or return default
 */
export function getYieldProof(key: string): PrivateYieldProof {
  return DEMO_YIELD_PROOFS[key] || DEMO_YIELD_PROOFS["default"];
}
